imports:
    - { resource: tables.yml }
services:
    alg.collapsecategories.listener:
        class: alg\collapsecategories\event\listener
        arguments:
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '@request'
            - '@config'
            - '%tables.collapse_forums_cat_status%'
            - '%tables.collapse_blocks%'
        tags:
            - { name: event.listener }
    alg.collapsecategories.collapsecategories_handler:
        class: alg\collapsecategories\controller\collapsecategories_handler
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@request'
            - '@config'
            - '@controller.helper'
            - '%tables.collapse_forums_cat_status%'
            - '%tables.collapse_blocks%'
