alg_collapsecategories_controller:
    path: /collapsecategories/{forum}/{status}/{user}
    defaults: { _controller: alg.collapsecategories.collapsecategories_handler:main }
    requirements:
        forum: \d+
alg_collapsecategories_controller_save:
    path: /collapsecategories/save
    defaults: { _controller: alg.collapsecategories.collapsecategories_handler:save_options }
alg_collapsecategories_controller_delete:
    path: /collapsecategories/delete
    defaults: { _controller: alg.collapsecategories.collapsecategories_handler:delete_block }
alg_collapsecategories_controller_add:
    path: /collapsecategories/add
    defaults: { _controller: alg.collapsecategories.collapsecategories_handler:add_block }
alg_collapsecategories_controller_edit:
    path: /collapsecategories/edit
    defaults: { _controller: alg.collapsecategories.collapsecategories_handler:edit_block }        